; =========================================================
; COLORS — paleta base (coherente con Alacritty)
; =========================================================
[colors]
bg = #1e1e1e
fg = #c5c8c6
gray = #5c6370
cyan = #61afef
red = #a86c6c


; =========================================================
; BAR — estructura general
; =========================================================
[bar/main]
width = 99%
height = 30
radius = 10

offset-x = 0.4%
offset-y = 1%

margin-left = 0
margin-right = 0
margin-top = 50

background = ${colors.bg}
foreground = ${colors.fg}

border-size = 1
line-size = 1
line-color = #6f8f8f

padding-left = 1
padding-right = 1

module-margin = 4

; Fuente unificada con terminal (consistencia visual total)
font-0 = JetBrainsMono Nerd Font Mono:size=14;4

modules-left = bspwm
modules-center = core
modules-right = wlan date

enable-ipc = true


; =========================================================
; BSPWM — workspaces (Opción C: híbrido limpio)
; =========================================================
[module/bspwm]
type = internal/bspwm
format = <label-state>

; ACTIVO → sólido + color acento
label-focused = "●"
label-focused-foreground = ${colors.cyan}
label-focused-margin = 1

; OCUPADO → sólido neutro
label-occupied = "●"
label-occupied-foreground = ${colors.fg}
label-occupied-margin = 1

; VACÍO → contorno sutil
label-empty = "○"
label-empty-foreground = ${colors.gray}
label-empty-margin = 1


; =========================================================
; CORE — centro (punto de interacción / “menú”)
; =========================================================
[module/core]
type = custom/text

; Branding mínimo (puede evolucionar después)
format = <label>
label = z0m4{OS}

label-foreground = ${colors.cyan} 
label-padding = 1

; Interacción (opcional pero útil)
click-left = rofi -show drun
click-right = rofi -show run


; =========================================================
; DATE — hora + estado de updates (sin ruido)
; =========================================================
[module/date]
type = custom/script
interval = 10

; Script unificado → decide color según estado
exec = ~/.config/polybar/scripts/updates.sh

; =====================================
; RED
;====================================

[module/wlan]
type = internal/network
interface = wlp3s0
interval = 3.0

; Formato conectado: muestra el icono y la IP
format-connected = <ramp-signal> <label-connected>
label-connected = %local_ip%
label-connected-foreground = ${colors.cyan}

; Formato desconectado
format-disconnected = <label-disconnected>
label-disconnected = 󰤮 OFF
label-disconnected-foreground = ${colors.gray}

; Iconos de señal
ramp-signal-0 = 󰤯
ramp-signal-1 = 󰤟
ramp-signal-2 = 󰤢
ramp-signal-3 = 󰤥
ramp-signal-4 = 󰤨
ramp-signal-foreground = ${colors.cyan}

click-left = sudo nmtui
